# Generated by Django 5.0.7 on 2024-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('salary', models.BigIntegerField()),
                ('hire_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('students', models.ManyToManyField(blank=True, related_name='teachers', to='student.student')),
            ],
        ),
    ]
