# Generated by Django 5.1 on 2024-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_students_alter_course_course_title_and_more"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="students",
        ),
        migrations.AddField(
            model_name="teacher",
            name="courses",
            field=models.ManyToManyField(
                related_name="assigned_course_teachers", to="course.course"
            ),
        ),
    ]
