# Generated by Django 5.0.7 on 2024-07-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='pic',
        ),
    ]
