# Generated by Django 5.0.7 on 2024-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='code',
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default='teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.CharField(default='Mary', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
