# Generated by Django 5.0.7 on 2024-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_code_teacher_bio_teacher_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.CharField(default='Ada Lab', max_length=20),
            preserve_default=False,
        ),
    ]
