# Generated by Django 5.0.7 on 2024-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_classperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classperiod',
        ),
    ]
