# Generated by Django 5.1 on 2024-08-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_course_id"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courseteachers",
                to="teacher.teacher",
            ),
        ),
    ]
