# Generated by Django 5.1 on 2024-08-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_students_alter_course_course_title_and_more"),
        ("teacher", "0002_remove_teacher_students_teacher_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courseteachers",
                to="teacher.teacher",
            ),
            preserve_default=False,
        ),
    ]
