# Generated by Django 5.0.7 on 2024-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='first_name',
            field=models.CharField(default='Jesus Christ', max_length=100),
            preserve_default=False,
        ),
    ]
