# Generated by Django 5.0.7 on 2024-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0002_classperiod_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='teacher',
            field=models.CharField(default='Mary Njiru', max_length=100),
            preserve_default=False,
        ),
    ]
