# Generated by Django 5.0.7 on 2024-08-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0003_initial'),
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom', to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='classroom.classroom'),
        ),
    ]
