# Generated by Django 5.0.7 on 2024-08-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0004_alter_classperiod_classroom_alter_classperiod_course'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_periods', to='course.course'),
            preserve_default=False,
        ),
    ]
