# Generated by Django 5.0.7 on 2024-08-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0007_alter_classperiod_teacher'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teacher', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
