# Generated by Django 5.0.7 on 2024-08-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='assigned_teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(default=1 , on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='course.course'),
            preserve_default=False,
        ),
    ]
