# Generated by Django 5.0.7 on 2024-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_delete_classs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
