# Generated by Django 5.1 on 2024-08-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0003_remove_classroom_assigned_teacher_classroom_course"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="course",
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms_assigned",
                to="teacher.teacher",
            ),
            preserve_default=False,
        ),
    ]
