# Generated by Django 5.1 on 2024-08-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0004_remove_classroom_course_classroom_teacher"),
        ("teacher", "0002_remove_teacher_students_teacher_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="first_name",
        ),
        migrations.AlterField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_assigned",
                to="teacher.teacher",
            ),
        ),
    ]
