# Generated by Django 5.1 on 2024-08-21 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_initial"),
        ("teacher", "0002_remove_teacher_students_teacher_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.AlterField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cassigned_teachers",
                to="teacher.teacher",
            ),
            preserve_default=False,
        ),
    ]
