# Generated by Django 5.0.7 on 2024-07-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_title',
        ),
    ]
