# Generated by Django 5.0.7 on 2024-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.TextField(default='I love JavaScript'),
            preserve_default=False,
        ),
    ]
