# Generated by Django 5.0.7 on 2024-08-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
    ]
