# Generated by Django 5.0.7 on 2024-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_courses_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.TextField(default='I love Pearl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
